In [9]:
import sagemaker
from sklearn.model_selection import train_test_split
import boto3
import pandas as pd
from sagemaker.core.helper.session_helper import Session

# Initialize clients
sm_boto3 = boto3.client("sagemaker")
sess = Session()
region = sess.boto_session.region_name
bucket = 'peddibuck'



print(f"Using bucket: {bucket}")
print(f"Using region: {region}")

Using bucket: peddibuck
Using region: us-east-1

In [10]:
df = pd.read_csv("C:/Users/ajays/OneDrive/Desktop/sagemaker ml model/mob_price_classification_train.csv")

In [11]:
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [12]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [13]:
df.shape

(2000, 21)

In [14]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [15]:
df.isnull().mean()*100

battery_power    0.0
blue             0.0
clock_speed      0.0
dual_sim         0.0
fc               0.0
four_g           0.0
int_memory       0.0
m_dep            0.0
mobile_wt        0.0
n_cores          0.0
pc               0.0
px_height        0.0
px_width         0.0
ram              0.0
sc_h             0.0
sc_w             0.0
talk_time        0.0
three_g          0.0
touch_screen     0.0
wifi             0.0
price_range      0.0
dtype: float64

In [16]:
features = list(df.columns)
features

['battery_power',
 'blue',
 'clock_speed',
 'dual_sim',
 'fc',
 'four_g',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'n_cores',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'three_g',
 'touch_screen',
 'wifi',
 'price_range']

In [17]:
label = features.pop(-1)
label

'price_range'

In [18]:
x = df[features]
y= df[label]

In [19]:
x.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0

In [20]:
y.head()

0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [21]:
x.shape

(2000, 20)

In [22]:
y.value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [23]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.15, random_state=0)

In [24]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1700, 20)
(300, 20)
(1700,)
(300,)

In [25]:
train_x = pd.DataFrame(X_train)
train_x[label] = y_train

test_x = pd.DataFrame(X_test)
test_x[label]= y_test

In [26]:
print(train_x.shape)
print(test_x.shape)

(1700, 21)
(300, 21)

In [27]:
train_x.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
1452,1450,0,2.1,0,1,0,31,0.6,114,5,...,1573,1639,794,11,5,9,0,1,1,1
1044,1218,1,2.8,1,3,0,39,0.8,150,7,...,1122,1746,1667,10,0,12,0,0,0,1
1279,1602,0,0.6,0,12,0,58,0.4,170,1,...,1259,1746,3622,17,2,17,0,1,1,3
674,1034,0,2.6,1,2,1,45,0.3,190,3,...,182,1293,969,15,1,7,1,0,0,0
1200,530,0,2.4,0,1,0,32,0.3,88,6,...,48,1012,959,17,7,6,0,1,0,0

In [28]:
train_x.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [29]:
test_x.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [30]:
train_x.to_csv("train-V-1.csv",index = False)
test_x.to_csv("test_V-1.csv", index= False)

In [31]:
# send data to S3. SageMaker will take training data from s3
sk_prefix = "sagemaker/mobile_price_classification/sklearncontainer"
trainpath = sess.upload_data(
    path="train-V-1.csv", bucket=bucket, key_prefix=sk_prefix
)

testpath = sess.upload_data(
    path="test_V-1.csv", bucket=bucket, key_prefix=sk_prefix
)
print(trainpath)
print(testpath)

s3://peddibuck/sagemaker/mobile_price_classification/sklearncontainer/train-V-1.csv
s3://peddibuck/sagemaker/mobile_price_classification/sklearncontainer/test_V-1.csv

In [32]:
%%writefile script.py

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score, roc_curve, auc
import sklearn
import joblib
import boto3
import pathlib
from io import StringIO 
import argparse
import joblib
import os
import numpy as np
import pandas as pd
    
def model_fn(model_dir):
    clf = joblib.load(os.path.join(model_dir, "model.joblib"))
    return clf
    
if __name__ == "__main__":

    print("[INFO] Extracting arguments")
    parser = argparse.ArgumentParser()

    # hyperparameters sent by the client are passed as command-line arguments to the script.
    parser.add_argument("--n_estimators", type=int, default=100)
    parser.add_argument("--random_state", type=int, default=0)

    # Data, model, and output directories
    parser.add_argument("--model-dir", type=str, default=os.environ.get("SM_MODEL_DIR"))
    parser.add_argument("--train", type=str, default=os.environ.get("SM_CHANNEL_TRAIN"))
    parser.add_argument("--test", type=str, default=os.environ.get("SM_CHANNEL_TEST"))
    parser.add_argument("--train-file", type=str, default="train-V-1.csv")
    parser.add_argument("--test-file", type=str, default="test_V-1.csv")

    args, _ = parser.parse_known_args()
    
    print("SKLearn Version: ", sklearn.__version__)
    print("Joblib Version: ", joblib.__version__)

    print("[INFO] Reading data")
    print()
    train_df = pd.read_csv(os.path.join(args.train, args.train_file))
    test_df = pd.read_csv(os.path.join(args.test, args.test_file))
    
    features = list(train_df.columns)
    label = features.pop(-1)
    
    print("Building training and testing datasets")
    print()
    X_train = train_df[features]
    X_test = test_df[features]
    y_train = train_df[label]
    y_test = test_df[label]

    print('Column order: ')
    print(features)
    print()
    
    print("Label column is: ",label)
    print()
    
    print("Data Shape: ")
    print()
    print("---- SHAPE OF TRAINING DATA (85%) ----")
    print(X_train.shape)
    print(y_train.shape)
    print()
    print("---- SHAPE OF TESTING DATA (15%) ----")
    print(X_test.shape)
    print(y_test.shape)
    print()
    
  
    print("Training RandomForest Model.....")
    print()
    model =  RandomForestClassifier(n_estimators=args.n_estimators, random_state=args.random_state, verbose = 3,n_jobs=-1)
    model.fit(X_train, y_train)
    print()
    

    model_path = os.path.join(args.model_dir, "model.joblib")
    joblib.dump(model,model_path)
    print("Model persisted at " + model_path)
    print()

    
    y_pred_test = model.predict(X_test)
    test_acc = accuracy_score(y_test,y_pred_test)
    test_rep = classification_report(y_test,y_pred_test)

    print()
    print("---- METRICS RESULTS FOR TESTING DATA ----")
    print()
    print("Total Rows are: ", X_test.shape[0])
    print('[TESTING] Model Accuracy is: ', test_acc)
    print('[TESTING] Testing Report: ')
    print(test_rep)

Overwriting script.py

In [ ]:
from sagemaker.sklearn.estimator import SKLearn

FRAMEWORK_VERSION = "1.2-1"

sklearn_estimator = SKLearn(
    entry_point="script.py",
    role="arn:aws:iam::010526247827:user/sagemaker-user",
    instance_count=1,
    instance_type="ml.m5.large",
    framework_version=FRAMEWORK_VERSION,
    base_job_name="RF-custom-sklearn",
    hyperparameters={
        "n_estimators": 100,
        "random_state": 0,
    },
    use_spot_instances = True,
    max_wait = 7200,
    max_run = 3600
)

In [36]:
# launch training job, with asynchronous call
sklearn_estimator.fit({"train": trainpath, "test": testpath}, wait=True)
# sklearn_estimator.fit({"train": datapath}, wait=True)

[03/04/26 12:43:23] INFO     SageMaker Python SDK will collect telemetry to help us better  telemetry_logging.py:94
                             understand our user's needs, diagnose issues, and deliver
                             additional features.
                             To opt out of telemetry, please disable via TelemetryOptOut
                             parameter in SDK defaults config. For more information, refer
                             to
                             https://sagemaker.readthedocs.io/en/stable/overview.html#confi
                             guring-and-using-defaults-with-the-sagemaker-python-sdk.

[03/04/26 12:43:25] INFO     Created S3 bucket: sagemaker-us-east-1-010526247827                     session.py:734

                    INFO     Creating training-job with name:                                       session.py:1270
                             RF-custom-sklearn-2026-03-04-18-43-23-341

[03/04/26 12:43:26] ERROR    Please check the troubleshooting guide for common errors:              session.py:1278
                             https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-python-sdk-t
                             roubleshooting.html#sagemaker-python-sdk-troubleshooting-create-traini
                             ng-job

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 # launch training job, with asynchronous call                                                │
│ ❱ 2 sklearn_estimator.fit({"train": trainpath, "test": testpath}, wait=True)                     │
│   3 # sklearn_estimator.fit({"train": datapath}, wait=True)                                      │
│   4                                                                                              │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\telemetry\telemetry_logging.py:170 in wrapper            │
│                                                                                                  │
│   167 │   │   │   │   │   caught_ex = e                                                          │
│   168 │   │   │   │   finally:                                                                   │
│   169 │   │   │   │   │   if caught_ex:                                                          │
│ ❱ 170 │   │   │   │   │   │   raise caught_ex                                                    │
│   171 │   │   │   │   │   return response  # pylint: disable=W0150                               │
│   172 │   │   │   else:                                                                          │
│   173 │   │   │   │   logger.debug(                                                              │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\telemetry\telemetry_logging.py:141 in wrapper            │
│                                                                                                  │
│   138 │   │   │   │   start_timer = perf_counter()                                               │
│   139 │   │   │   │   try:                                                                       │
│   140 │   │   │   │   │   # Call the original function                                           │
│ ❱ 141 │   │   │   │   │   response = func(*args, **kwargs)                                       │
│   142 │   │   │   │   │   stop_timer = perf_counter()                                            │
│   143 │   │   │   │   │   elapsed = stop_timer - start_timer                                     │
│   144 │   │   │   │   │   extra += f"&x-latency={round(elapsed, 2)}"                             │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\workflow\pipeline_context.py:346 in wrapper              │
│                                                                                                  │
│   343 │   │   │                                                                                  │
│   344 │   │   │   return _StepArguments(retrieve_caller_name(self_instance), run_func, *args,    │
│   345 │   │                                                                                      │
│ ❱ 346 │   │   return run_func(*args, **kwargs)                                                   │
│   347 │                                                                                          │
│   348 │   return wrapper                                                                         │
│   349                                                                                            │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\estimator.py:1422 in fit                                 │
│                                                                                                  │
│   1419 │   │   self._prepare_for_training(job_name=job_name)                                     │
│   1420 │   │                                                                                     │
│   1421 │   │   experiment_config = check_and_get_run_experiment_config(experiment_config)        │
│ ❱ 1422 │   │   self.latest_training_job = _TrainingJob.start_new(self, inputs, experiment_confi  │
│   1423 │   │   self.jobs.append(self.latest_training_job)                                        │
│   1424 │   │   forward_to_mlflow_tracking_server = False                                         │
│   1425 │   │   if os.environ.get("MLFLOW_TRACKING_URI") and self.enable_network_isolation():     │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\estimator.py:2575 in start_new                           │
│                                                                                                  │
│   2572 │   │   train_args = cls._get_train_args(estimator, inputs, experiment_config)            │
│   2573 │   │                                                                                     │
│   2574 │   │   logger.debug("Train args after processing defaults: %s", train_args)              │
│ ❱ 2575 │   │   estimator.sagemaker_session.train(**train_args)                                   │
│   2576 │   │                                                                                     │
│   2577 │   │   return cls(estimator.sagemaker_session, estimator._current_job_name)              │
│   2578                                                                                           │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\session.py:1283 in train                                 │
│                                                                                                  │
│   1280 │   │   │   │   )                                                                         │
│   1281 │   │   │   │   raise e                                                                   │
│   1282 │   │                                                                                     │
│ ❱ 1283 │   │   self._intercept_create_request(train_request, submit, self.train.__name__)        │
│   1284 │                                                                                         │
│   1285 │   def _get_train_request(  # noqa: C901                                                 │
│   1286 │   │   self,                                                                             │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\session.py:7040 in _intercept_create_request             │
│                                                                                                  │
│   7037 │   │   │   create (functor): a functor calls the sagemaker client create method          │
│   7038 │   │   │   func_name (str): the name of the function needed intercepting                 │
│   7039 │   │   """                                                                               │
│ ❱ 7040 │   │   return create(request)                                                            │
│   7041 │                                                                                         │
│   7042 │   def _create_inference_recommendations_job_request(                                    │
│   7043 │   │   self,                                                                             │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\session.py:1281 in submit                                │
│                                                                                                  │
│   1278 │   │   │   │   logger.error(                                                             │
│   1279 │   │   │   │   │   "Please check the troubleshooting guide for common errors: %s", trou  │
│   1280 │   │   │   │   )                                                                         │
│ ❱ 1281 │   │   │   │   raise e                                                                   │
│   1282 │   │                                                                                     │
│   1283 │   │   self._intercept_create_request(train_request, submit, self.train.__name__)        │
│   1284                                                                                           │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\sagemaker\session.py:1272 in submit                                │
│                                                                                                  │
│   1269 │   │   │   try:                                                                          │
│   1270 │   │   │   │   logger.info("Creating training-job with name: %s", job_name)              │
│   1271 │   │   │   │   logger.debug("train request: %s", json.dumps(request, indent=4))          │
│ ❱ 1272 │   │   │   │   self.sagemaker_client.create_training_job(**request)                      │
│   1273 │   │   │   except Exception as e:                                                        │
│   1274 │   │   │   │   troubleshooting = (                                                       │
│   1275 │   │   │   │   │   "https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-python-sd  │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\botocore\client.py:602 in _api_call                                │
│                                                                                                  │
│    599 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    600 │   │   │   │   )                                                                         │
│    601 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  602 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    603 │   │                                                                                     │
│    604 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    605                                                                                           │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\botocore\context.py:123 in wrapper                                 │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ c:\Users\ajays\OneDrive\Desktop\sagemaker ml                                                     │
│ model\.venv\Lib\site-packages\botocore\client.py:1078 in _make_api_call                          │
│                                                                                                  │
│   1075 │   │   │   │   'error_code_override'                                                     │
│   1076 │   │   │   ) or error_info.get("Code")                                                   │
│   1077 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1078 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1079 │   │   else:                                                                             │
│   1080 │   │   │   return parsed_response                                                        │
│   1081                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: 1 validation
error detected: Value 'arn:aws:iam::010526247827:user/sagemaker-user' at 'roleArn' failed to satisfy constraint:
Member must satisfy regular expression pattern: arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+